--liquibase formatted sql

--changeset codex:034-deterministic-planner
ALTER TABLE training_proposals DROP CONSTRAINT IF EXISTS training_proposals_source_ai;
ALTER TABLE training_proposals DROP CONSTRAINT IF EXISTS training_proposals_source_check;
ALTER TABLE training_proposals ALTER COLUMN source TYPE VARCHAR(16);
ALTER TABLE training_proposals ADD CONSTRAINT training_proposals_source_check
  CHECK (source IN ('AI','COACH','RULE_BASED'));

ALTER TABLE calendar_draft_jobs DROP CONSTRAINT calendar_draft_jobs_state_check;
ALTER TABLE calendar_draft_jobs ADD CONSTRAINT calendar_draft_jobs_state_check
  CHECK(state IN ('QUEUED','RUNNING','READY','FAILED','SUPERSEDED','STALE','EXPIRED','IMPOSSIBLE'));
ALTER TABLE calendar_draft_jobs ADD COLUMN protocol INTEGER NOT NULL DEFAULT 1 CHECK (protocol IN (1,2));
ALTER TABLE calendar_draft_jobs ADD COLUMN variant INTEGER NOT NULL DEFAULT 0 CHECK (variant >= 0);
ALTER TABLE calendar_draft_jobs ADD COLUMN execution_snapshot JSONB;

CREATE TABLE planner_builtin_exercise_mappings (
  exercise_id UUID PRIMARY KEY,
  movement_class VARCHAR(32) NOT NULL,
  roles JSONB NOT NULL,
  supported_goals JSONB NOT NULL,
  exercise_type VARCHAR(16) NOT NULL,
  equipment_ids JSONB NOT NULL,
  revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE planner_owner_exercise_mappings (
  owner_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  exercise_id UUID NOT NULL,
  movement_class VARCHAR(32) NOT NULL,
  roles JSONB NOT NULL,
  supported_goals JSONB NOT NULL,
  exercise_type VARCHAR(16) NOT NULL,
  equipment_ids JSONB NOT NULL,
  revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY(owner_id, exercise_id)
);
CREATE INDEX planner_owner_exercise_mappings_exercise
  ON planner_owner_exercise_mappings(exercise_id);


ALTER TABLE calendar_draft_jobs ADD COLUMN raw_request BYTEA;
ALTER TABLE calendar_draft_jobs ADD COLUMN request_kind VARCHAR(16) NOT NULL DEFAULT 'CREATE';
ALTER TABLE calendar_draft_jobs ADD COLUMN base_proposal_id UUID;

-- Reviewed UUIDs from CanonicalExerciseRegistry and explicit CanonicalEquipmentRequirements.
-- Seed missing classification only; operator edits survive every deployment.
INSERT INTO planner_builtin_exercise_mappings(exercise_id,movement_class,roles,supported_goals,exercise_type,equipment_ids) VALUES
('99858342-091a-3b09-a60e-2e94877b7c79','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "flat_bench", "rack"]'::jsonb),
('1bccc5ae-dbd0-305b-80f3-4642a52117cf','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells", "flat_bench"]'::jsonb),
('631796b2-7c61-32ba-acd1-2aefe68fcbca','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "incline_bench", "rack"]'::jsonb),
('1e5626e6-5681-321e-8b0b-8879737e8f20','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells", "incline_bench"]'::jsonb),
('d3cb58ff-4faf-35a0-8ac0-64438a420835','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('fe09eeb8-44b0-32f3-873e-eed71e92d5dc','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["chest_press_machine"]'::jsonb),
('b9b24431-4e37-3892-94c1-5cb2a6f6fd46','VERTICAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["pullup_bar"]'::jsonb),
('f35b61c7-9dda-3ab1-bbd9-f8da6b0bb970','VERTICAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["pullup_bar"]'::jsonb),
('19a0a043-47d4-333c-99d1-97066ee42456','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell"]'::jsonb),
('19007699-766d-315e-a0e4-7c6dcf840ccd','VERTICAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["upper_pulley"]'::jsonb),
('816c93ca-28b4-3b34-99ad-e7e409a95b06','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["lower_pulley"]'::jsonb),
('0205ff0e-091a-32ff-8536-111b581962ee','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells", "flat_bench"]'::jsonb),
('02aeafc6-b39e-38f4-ac3f-ea4e7e6b5d5c','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell"]'::jsonb),
('94b441df-ae71-3660-8be5-095bc3cfbb72','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["t_bar_machine"]'::jsonb),
('081766f5-34a7-3c1f-8630-a595202c3b4a','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["hyperextension_bench"]'::jsonb),
('e231c9ab-2108-31a7-9f35-92a80eab4add','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "rack"]'::jsonb),
('3fa2fd53-154d-3a76-8898-9de571b836af','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["smith_machine"]'::jsonb),
('160a57a6-94a1-3ae4-b89e-e86420e0a26d','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["hack_squat"]'::jsonb),
('54b2cb24-8bf4-3d4d-b814-85d5300bea87','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["leg_press"]'::jsonb),
('edfc58ab-6cc0-33ed-b139-08c90d5f87af','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells"]'::jsonb),
('ba215d24-d12e-320e-bd7b-9fe3a905c58c','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["flat_bench"]'::jsonb),
('1b7b3b47-da74-312e-a7a4-b87f3e941cb8','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell"]'::jsonb),
('46381200-6c68-322a-9e52-25b7e547f07e','VERTICAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell"]'::jsonb),
('59eefd82-3d0b-35f9-951d-ebd1e813e5fe','VERTICAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells", "flat_bench"]'::jsonb),
('f2015666-0f2a-3b14-9a1e-695d41a74139','VERTICAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells", "flat_bench"]'::jsonb),
('f849af0c-f889-3916-99aa-545e2e6bc975','VERTICAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells"]'::jsonb),
('f60ee68e-8cd4-3fb1-a771-12b21a9469d6','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('1a78e166-3d4a-3638-9c48-30bf84497a14','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["upper_pulley"]'::jsonb),
('4fca155a-748c-39da-8084-d18e140cdab0','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["pullup_bar"]'::jsonb),
('5094c9e8-9805-3c70-a162-0266558b24b7','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('1bd20705-3bea-36ff-b21a-4fb9192f9d33','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('01ac61f4-1450-3134-81fa-4848dcc5c2fa','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('6c9dc8f3-eed1-3dbd-8a51-469d76844f6f','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('aaf4fd5a-5b30-32e3-8295-c232be7616c1','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'TIMED','[]'::jsonb),
('51b6a4dc-e4bf-3424-bee9-e9c13a6f11b7','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'TIMED','[]'::jsonb),
('1ec6f027-4362-3bb4-8776-f2956fe9a80b','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["treadmill"]'::jsonb),
('84b937ac-91d1-3d72-b03d-f0e3cc7aa9f9','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["exercise_bike"]'::jsonb),
('b0852342-1aae-387e-9e38-8f5a46e8ad21','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["elliptical"]'::jsonb),
('c0165bac-b931-30b6-a2a5-602cfdca049c','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["rowing_machine"]'::jsonb),
('cb9c6491-f330-3171-b58a-e66429c62e57','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["stepper"]'::jsonb),
('6798318b-0569-3642-b1c7-c28a0d7b229e','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["box"]'::jsonb),
('fa5de7df-bf48-3ffa-a1ce-87d27df3af54','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "flat_bench", "rack"]'::jsonb),
('241ca41e-8c89-3370-932d-1db4eec50f0e','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "incline_bench", "rack"]'::jsonb),
('fa5b05e6-0740-3326-b3cc-9ed2f9e3a1b5','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells", "flat_bench"]'::jsonb),
('c280c283-a729-3e35-b6a5-af7820d77206','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["decline_bench", "dumbbells"]'::jsonb),
('352daea2-a130-3b83-9dcc-95ba548e4e03','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["incline_bench", "smith_machine"]'::jsonb),
('d690ecb2-7ec3-367f-99ab-4f4f3dae7a8c','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["flat_bench", "smith_machine"]'::jsonb),
('15985a20-53f3-39b2-ad12-758b95bf0cff','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dip_bars"]'::jsonb),
('a24837fa-8257-32ff-85ed-60be7d05fbfe','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["plates"]'::jsonb),
('f777269a-0a28-36e7-bbfe-aa1265736312','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["chest_press_machine"]'::jsonb),
('dfae59c5-d1d9-3f60-951d-536f503b3ae4','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["flat_bench"]'::jsonb),
('2f7be1e8-70ce-3632-955d-241ac33c5023','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["chest_press_machine"]'::jsonb),
('3ec4fc5e-908f-3dc3-b390-cf9ee40fae90','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells", "flat_bench"]'::jsonb),
('695e70a0-4d60-362f-89b5-0cb55f4932bf','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "decline_bench", "rack"]'::jsonb),
('7a6770ad-dd94-381c-9f2b-73f86f7e646d','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["flat_bench", "smith_machine"]'::jsonb),
('bafc7201-dad6-3073-8049-187204052c73','VERTICAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell"]'::jsonb),
('825e2b5e-70ff-3513-9e45-322c40adc0f2','VERTICAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["shoulder_press_machine"]'::jsonb),
('a77c81bd-b7da-30dc-a04d-0a36d0763a3a','VERTICAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["flat_bench", "smith_machine"]'::jsonb),
('a44abb95-4a4c-30ad-9c25-958243019176','VERTICAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["upper_pulley"]'::jsonb),
('37780a09-5146-3b71-b088-3245943e9b1d','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["row_machine"]'::jsonb),
('dc25784a-ccde-354d-bad8-0e2ccf3ded99','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells"]'::jsonb),
('af7cf2b3-6b85-38fd-8ff3-1675499f0243','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells", "incline_bench"]'::jsonb),
('3c0667ce-83b6-3c8a-b608-ed2969d3144e','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell"]'::jsonb),
('43ce7418-93a2-3ac7-ab3a-05d1fa3e1b96','VERTICAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["pullup_bar"]'::jsonb),
('2b55e441-4857-33da-b8b2-766706284828','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["row_machine"]'::jsonb),
('877981dc-62bf-3d54-82ed-0b8c03c5e326','VERTICAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["upper_pulley"]'::jsonb),
('2af2b2a7-c490-3c2f-abf5-3fbc53ca43cd','VERTICAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["pullup_bar"]'::jsonb),
('85da42a0-0b2d-3e81-989f-f04a4216f3a1','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["lower_pulley"]'::jsonb),
('d0a4c2b3-d723-3b03-a452-bea4e8cb6cc0','VERTICAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["upper_pulley"]'::jsonb),
('588f5e83-7c72-35c9-bdf3-13020fb3e391','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["crossover"]'::jsonb),
('2c24e9b2-1a67-3bd1-ab4e-1d3d898cd1f5','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["lower_pulley"]'::jsonb),
('3788e0fa-e638-3b45-be13-6d0773a3cc1d','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["reverse_hyper"]'::jsonb),
('a912925e-8159-3d1d-936c-7ef1626184e5','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["back_extension_machine"]'::jsonb),
('1fc5acd9-53d3-3c98-8239-c3b910049b63','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["lower_pulley"]'::jsonb),
('11b25d6c-0969-30e1-8d4b-9f793bec15d6','VERTICAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["gravitron"]'::jsonb),
('9d7b924d-ea0b-3955-aac4-e6e009fe8713','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "rack"]'::jsonb),
('2cc41bd8-8a16-3fc8-92cc-4d77630d159b','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["smith_machine"]'::jsonb),
('7e0aabee-bffa-306f-baae-9fa12420a73b','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "rack"]'::jsonb),
('3ee6a806-8287-3d42-a674-a18e91b73366','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["kettlebell"]'::jsonb),
('03d9071e-b142-3bce-98ad-f09bd43031da','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "rack"]'::jsonb),
('42360fca-0f20-321c-adcb-b3ce102aedea','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["kettlebell"]'::jsonb),
('7619675d-7c18-301a-aede-9bf13827ba82','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell"]'::jsonb),
('7784b561-5b50-3391-a8a8-6a0e155465e4','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["trap_bar"]'::jsonb),
('e4aa0559-7d85-3b91-a0ca-8cbb4ce1a63d','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["trap_bar"]'::jsonb),
('9441cad1-4fbc-3893-a1c9-a7859b2ce4a5','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells"]'::jsonb),
('e757cfa0-42e3-3e34-a65b-d4bff2513e06','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('b51285c6-5ba9-3849-a1ef-6f94f6db9624','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["hip_thrust_machine"]'::jsonb),
('73236e48-cfb1-3a5e-b331-6216ebea3377','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["flat_bench", "smith_machine"]'::jsonb),
('d0ca1d2d-8b0b-3921-a507-a8e901ffaf92','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["box", "kettlebell"]'::jsonb),
('111e7e2f-94fb-3c93-b5d5-697b20a8f227','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["box"]'::jsonb),
('ec4e9b3d-f041-31f8-b900-f9a5205e1c4b','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells"]'::jsonb),
('64901e5a-ecc5-38a2-9665-92ba65cdf8ab','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('2a545db8-084d-37f3-be56-7037b7f81265','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["resistance_band"]'::jsonb),
('64996a00-49cf-30b5-8ec8-7f43c9bcfb53','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["crossover"]'::jsonb),
('b0ee4ffd-d485-3f4b-9338-14e508f25ec0','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["ab_wheel"]'::jsonb),
('d2d3b2b0-550f-3a57-aa57-a763e9f04684','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["ab_wheel"]'::jsonb),
('1477f8ff-60c3-3a95-9bf1-4df8a528cb91','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells"]'::jsonb),
('3c4e0b56-a574-337b-8985-d33a09e60d67','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["kettlebell"]'::jsonb),
('e22bc510-499f-3155-9b67-ce7cce4abe63','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["plates"]'::jsonb),
('4155fc7b-e5c4-3531-ad10-9e491d663657','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["plates"]'::jsonb),
('ea90e0a0-8b41-32ae-ba38-4d97b6c1b488','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["crossover"]'::jsonb),
('6ee73297-de91-37dc-b0f4-d226093cd267','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('9b9ab828-d623-32e2-9a6a-f2ecbc2fa368','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["pullup_bar"]'::jsonb),
('5a07ccb3-74a9-36ac-be19-6d8d73a672ba','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["captains_chair"]'::jsonb),
('0528dfca-d90d-3d58-9a9d-83eacfbbf416','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('6dafab03-ce87-3029-8110-0216aaaab7a2','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('bf3fa9bd-5123-360d-b85e-b576abc80e5e','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["resistance_band"]'::jsonb),
('0987628d-6693-3455-8e56-a2823a593264','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells"]'::jsonb),
('aaec574b-2b7b-3212-92de-3e1b3646429f','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["kettlebell"]'::jsonb),
('74737f1b-d1a1-3562-a5c3-7c0fdec67bae','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "rack"]'::jsonb),
('856aacb2-1eb7-312f-a016-951815c15508','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "rack"]'::jsonb),
('695008f5-d609-34e4-bcda-9e011cca8a55','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "flat_bench", "rack"]'::jsonb),
('bc112e80-948e-3720-91dc-a027c374fdac','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "flat_bench", "rack"]'::jsonb),
('ca7aabff-0e65-375e-9c87-32e69589c036','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell"]'::jsonb),
('5dda527e-1d2a-3270-bb1a-cc972ba9dc8a','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell"]'::jsonb),
('d874172c-63ef-341f-8c98-23936e52f927','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "flat_bench", "rack"]'::jsonb),
('0fc4e140-4056-3ac9-8884-503de6b3df39','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "flat_bench", "rack"]'::jsonb),
('8ccf25d7-fbaa-3db3-8a53-48a3dd328847','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell"]'::jsonb),
('1016f195-71cb-343b-b603-f5d2e4d07145','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell"]'::jsonb),
('4bc90ba0-b7e2-3fd0-898e-7ce4fcb8fba7','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "box", "rack"]'::jsonb),
('5bf4fe5e-28e8-3559-abe4-3e0a75dfb6be','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "board", "flat_bench", "rack"]'::jsonb),
('d8b976e0-181c-342d-b63e-eec77f6b64d8','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "platform"]'::jsonb),
('b8e3ed75-045b-31b9-b615-b5824f5427d8','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "blocks"]'::jsonb),
('198952a3-34ea-3bc1-b823-ebc81ccbe7b6','HIP_HINGE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "blocks"]'::jsonb),
('81059258-28e8-33b9-823c-7f7db4ba9845','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "flat_bench", "rack"]'::jsonb),
('3e2bbd73-14f5-373b-9bf1-09946ec8feda','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["dumbbells", "flat_bench"]'::jsonb),
('3e5e5d6b-7eb0-3b79-9be6-fabf0089f423','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["barbell", "rack"]'::jsonb),
('ddf13635-44ef-3331-a1d3-e68a52931077','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["smith_machine"]'::jsonb),
('6f7b1495-07fa-3fe7-a069-e44517aa6149','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["leg_press"]'::jsonb),
('29a2093c-b84a-39da-aa5b-3f602017128a','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["leg_press"]'::jsonb),
('a11382f9-27b0-3cd1-ab90-c724e44251f9','VERTICAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["rings"]'::jsonb),
('062a2127-7106-3f23-a6d6-9d9aeeda1f0c','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["rings"]'::jsonb),
('84d16e0f-a845-362c-bcc7-05121a924645','HORIZONTAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["rings"]'::jsonb),
('600e1d64-294f-3e70-b645-9d80cd3676f8','VERTICAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["rings"]'::jsonb),
('429b14be-5843-359d-884a-39dab21bb49c','VERTICAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('2d261a9f-3216-36fc-9002-8f4f035705c0','VERTICAL_PUSH','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('310dd51b-a65e-3c61-b1ff-8ddc27f97671','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('85862c0a-3da8-363e-b753-6b0f5225c521','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["support"]'::jsonb),
('5b50a8f5-7fd8-351a-b1eb-861f21a569b8','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["low_bar"]'::jsonb),
('7ff25624-9d71-3b44-8311-30483754e3f8','HORIZONTAL_PULL','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["rings"]'::jsonb),
('16cf81a7-42e1-346c-b029-838f74c1b673','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('f4ef78c1-92c0-3bfb-9892-8cb33c11a08d','CORE','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','["parallettes"]'::jsonb),
('25b9ceb3-2598-335d-97c7-525512b6939c','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('32a2ad8a-20b8-36cf-9b82-536640ec37a4','SQUAT','["ACCESSORY", "PRIMARY"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'STRENGTH','[]'::jsonb),
('37111b8d-587a-3167-973a-78d4e67f2fcb','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["treadmill"]'::jsonb),
('97edf3d7-45c9-350f-893c-353c6302550d','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["treadmill"]'::jsonb),
('8c53a6f2-988f-3d23-af4c-74c0cbb86b17','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["treadmill"]'::jsonb),
('042334a2-28ff-3cdc-80b1-952024fe13f3','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["treadmill"]'::jsonb),
('e5b15751-0c3b-3159-a9f8-2a69093d4cd0','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["exercise_bike"]'::jsonb),
('e33c19a6-a134-3673-9d4a-81e4796df90f','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["exercise_bike"]'::jsonb),
('d5245d95-02ad-3200-bef9-4b413e51cfa7','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["rowing_machine"]'::jsonb),
('bb83f6af-00ac-305a-a7d5-ac54187060d7','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["rowing_machine"]'::jsonb),
('efb570f9-7538-32d1-b11b-262cf1fd15cd','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["stair_climber"]'::jsonb),
('28ffcba6-2574-3994-9257-f282656ff3ff','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["stepper"]'::jsonb),
('61491d47-5075-3675-826d-749fb45f2726','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["jump_rope"]'::jsonb),
('f4190639-4522-3d30-8ab2-320438ba7db6','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["jump_rope"]'::jsonb),
('05027455-89e7-3886-9486-c74fa8e58382','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["air_bike"]'::jsonb),
('1600ba7f-ac85-39cf-bb44-49c075d51da7','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["air_bike"]'::jsonb),
('bbe36748-97f2-3e9f-bf8c-b2f45434b794','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["ski_erg"]'::jsonb),
('75c2e1f2-47af-347a-bce0-0381c269b7f6','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["ski_erg"]'::jsonb),
('dd20895e-7c2c-3ad3-b693-0d79d42ec195','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["elliptical"]'::jsonb),
('be204362-08b5-3af1-b5e7-4818d87db9e3','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["elliptical"]'::jsonb),
('669c0412-5bab-3bc9-916f-c572ae69cb5f','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','[]'::jsonb),
('3fa6a397-2efb-3786-96d9-58f7ccb33380','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["treadmill"]'::jsonb),
('581cee0d-c0d4-3e0d-9e49-ad82ae91da8f','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','[]'::jsonb),
('6df85df8-bd3d-3d06-aece-d73422d57c33','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','[]'::jsonb),
('51ba7323-2ad6-3ec8-823d-c475ed71ec3e','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["stepper"]'::jsonb),
('e3797bae-3d63-3034-809b-d658ddb35493','CARDIO','["CONDITIONING"]'::jsonb,'["ENDURANCE", "FAT_LOSS", "GENERAL_FITNESS", "MUSCLE_GAIN", "STRENGTH"]'::jsonb,'CARDIO','["pool"]'::jsonb)
ON CONFLICT(exercise_id) DO NOTHING;
